# Generated by Django 2.2.6 on 2019-11-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20191105_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Amount',
            new_name='amount',
        ),
    ]
